name: Docs deploy

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yml"

jobs:
  docs:
    uses: KsQRooW/python-workflow/.github/workflows/docs.yml@main
    permissions:
      contents: write
    with:
      python_version: "3.12"
      packaging_with: "poetry"
      from: "docs"
